services:
  web:
    build: .
    container_name: hp_challenge
    env_file:
      - .env.example
    volumes:
      - .:/core
      - ./data:/core/data
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py load_pokemon &&
             python manage.py runserver 0.0.0.0:8000"
    