# Generated by Django 6.0.1 on 2026-01-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('reversed_name', models.CharField(max_length=100)),
            ],
        ),
    ]
